name = "wakoshi-implant"
pages_build_output_dir = "public"

# Cloudflare Account ID: 1e645d153a173af4db10240f6adf81cd
# Cloudflare Email: skywalker19871224@gmail.com
# Git Account: dom19630618-hub

account_id = "1e645d153a173af4db10240f6adf81cd"
