name = "wakoshi-implant"
pages_build_output_dir = "public"

# Cloudflare Account ID: 936e369e3f65741309936fa4e241f16b
# Cloudflare Email: dom19630618@gmail.com
# Git Account: dom19630618-hub

account_id = "936e369e3f65741309936fa4e241f16b"
